name: Deploy on push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Kill waitress-serve process
      run: pkill waitress-serve || true
    - name: Kill chrome process
      run: pkill chrome || true
    - name: Copy all from current folder to /home/slave/fish-hunter-flask exclude .git folder
      run: rsync -av --progress . /home/slave/fish-hunter-flask --exclude .git
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Touch trigger update
      run: touch /home/slave/fish-hunter-flask/trigger_update