name: Deploy on push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Stopping old docker container
      run: docker stop /hunter_flask || true
    - name: Removing old docker container
      run: docker rm /hunter_flask || true
    - name: Build docker images
      run: docker build -t fish-hunter-flask:1.0.0 .
    - name: Run docker
      run: docker run -itd -v /home/slave/fish-hunter-flask/.env:/fish-hunter/.env -p 8080:8080 --name hunter_flask fish-hunter-flask:1.0.0
    - name: Removing none tagged docker images
      run: docker rmi $(docker images | grep '<none>' | tr -s ' ' | cut -d ' ' -f 3) || true