name: Deploy on push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Kill waitress-serve process
      run: pkill waitress-serve || true
    - name: Kill chrome process
      run: pkill chrome || true
    - name: Copy all from current folder to /home/slave/fish-hunter-flask exclude .git folder
      run: rsync -av --progress . /home/slave/fish-hunter-flask --exclude .git
    - name: Change directory to /home/slave/fish-hunter-flask
      run: cd /home/slave/fish-hunter-flask
    - name: Run the waitress-serve in background
      run: waitress-serve --call 'app:create_app' &