name: Deploy on push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Kill waitress-serve process
      continue-on-error: true
      run: docker exec fhf pkill waitress-serve
    - name: Kill chrome process
      continue-on-error: true
      run: docker exec fhf pkill chrome
    - name: Copy files to docker container
      run: docker cp . fhf:/app
    - name: Install requirements
      run: docker exec fhf pip install -r requirements.txt
    - name: Run flask app in screen session
      run: docker exec -itd fhf screen -dmS waitress-serve waitress-serve --call 'app:create_app'